package defpackage;

import j$.util.DesugarCollections;
import java.security.GeneralSecurityException;
import java.util.HashMap;
import java.util.Set;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class dpr {
    static {
        dvo dvoVar = dvo.a;
        try {
            a();
        } catch (GeneralSecurityException e) {
            throw new ExceptionInInitializerError(e);
        }
    }

    public static void a() {
        drs.a.c(dpt.a);
        drs.a.b(dpt.b);
        drs.a.c(dpv.a);
        drs.a.b(dpv.b);
        dlq.a();
        dou.a();
        if (dop.a()) {
            return;
        }
        dsa dsaVar = doz.a;
        if (!doo.a(doo.a)) {
            throw new GeneralSecurityException("Registering ECIES Hybrid Encryption is not supported in FIPS mode");
        }
        drx drxVar = dqe.a;
        drt drtVar = drt.a;
        drtVar.e(dqe.a);
        drtVar.f(dqe.b);
        drtVar.g(dqe.c);
        drtVar.h(dqe.e);
        drtVar.g(dqe.d);
        drtVar.h(dqe.f);
        drr drrVar = drr.a;
        HashMap map = new HashMap();
        Set set = dpf.a;
        dpa dpaVar = new dpa();
        dpaVar.a = dpb.a;
        dpaVar.b = dpc.c;
        dpaVar.c = dpd.b;
        dpaVar.e = dpe.a;
        enh enhVar = new enh((char[]) null, (byte[]) null);
        enhVar.k();
        enhVar.l(16);
        enhVar.m();
        enhVar.c = dmg.c;
        dpaVar.b(enhVar.j());
        map.put("ECIES_P256_HKDF_HMAC_SHA256_AES128_GCM", dpaVar.a());
        dpa dpaVar2 = new dpa();
        dpaVar2.a = dpb.a;
        dpaVar2.b = dpc.c;
        dpaVar2.c = dpd.b;
        dpaVar2.e = dpe.c;
        enh enhVar2 = new enh((char[]) null, (byte[]) null);
        enhVar2.k();
        enhVar2.l(16);
        enhVar2.m();
        enhVar2.c = dmg.c;
        dpaVar2.b(enhVar2.j());
        map.put("ECIES_P256_HKDF_HMAC_SHA256_AES128_GCM_RAW", dpaVar2.a());
        dpa dpaVar3 = new dpa();
        dpaVar3.a = dpb.a;
        dpaVar3.b = dpc.c;
        dpaVar3.c = dpd.a;
        dpaVar3.e = dpe.a;
        enh enhVar3 = new enh((char[]) null, (byte[]) null);
        enhVar3.k();
        enhVar3.l(16);
        enhVar3.m();
        enhVar3.c = dmg.c;
        dpaVar3.b(enhVar3.j());
        map.put("ECIES_P256_COMPRESSED_HKDF_HMAC_SHA256_AES128_GCM", dpaVar3.a());
        dpa dpaVar4 = new dpa();
        dpaVar4.a = dpb.a;
        dpaVar4.b = dpc.c;
        dpaVar4.c = dpd.a;
        dpaVar4.e = dpe.c;
        enh enhVar4 = new enh((char[]) null, (byte[]) null);
        enhVar4.k();
        enhVar4.l(16);
        enhVar4.m();
        enhVar4.c = dmg.c;
        dpaVar4.b(enhVar4.j());
        map.put("ECIES_P256_COMPRESSED_HKDF_HMAC_SHA256_AES128_GCM_RAW", dpaVar4.a());
        dpa dpaVar5 = new dpa();
        dpaVar5.a = dpb.a;
        dpaVar5.b = dpc.c;
        dpaVar5.c = dpd.a;
        dpaVar5.e = dpe.c;
        enh enhVar5 = new enh((char[]) null, (byte[]) null);
        enhVar5.k();
        enhVar5.l(16);
        enhVar5.m();
        enhVar5.c = dmg.c;
        dpaVar5.b(enhVar5.j());
        map.put("ECIES_P256_HKDF_HMAC_SHA256_AES128_GCM_COMPRESSED_WITHOUT_PREFIX", dpaVar5.a());
        dpa dpaVar6 = new dpa();
        dpaVar6.a = dpb.a;
        dpaVar6.b = dpc.c;
        dpaVar6.c = dpd.b;
        dpaVar6.e = dpe.a;
        dpa dpaVar7 = new dpa(null);
        dpaVar7.d(16);
        dpaVar7.e(32);
        dpaVar7.g(16);
        dpaVar7.f(16);
        dpaVar7.a = dlv.c;
        dpaVar7.f = dlw.c;
        dpaVar6.b(dpaVar7.c());
        map.put("ECIES_P256_HKDF_HMAC_SHA256_AES128_CTR_HMAC_SHA256", dpaVar6.a());
        dpa dpaVar8 = new dpa();
        dpaVar8.a = dpb.a;
        dpaVar8.b = dpc.c;
        dpaVar8.c = dpd.b;
        dpaVar8.e = dpe.c;
        dpa dpaVar9 = new dpa(null);
        dpaVar9.d(16);
        dpaVar9.e(32);
        dpaVar9.g(16);
        dpaVar9.f(16);
        dpaVar9.a = dlv.c;
        dpaVar9.f = dlw.c;
        dpaVar8.b(dpaVar9.c());
        map.put("ECIES_P256_HKDF_HMAC_SHA256_AES128_CTR_HMAC_SHA256_RAW", dpaVar8.a());
        dpa dpaVar10 = new dpa();
        dpaVar10.a = dpb.a;
        dpaVar10.b = dpc.c;
        dpaVar10.c = dpd.a;
        dpaVar10.e = dpe.a;
        dpa dpaVar11 = new dpa(null);
        dpaVar11.d(16);
        dpaVar11.e(32);
        dpaVar11.g(16);
        dpaVar11.f(16);
        dpaVar11.a = dlv.c;
        dpaVar11.f = dlw.c;
        dpaVar10.b(dpaVar11.c());
        map.put("ECIES_P256_COMPRESSED_HKDF_HMAC_SHA256_AES128_CTR_HMAC_SHA256", dpaVar10.a());
        dpa dpaVar12 = new dpa();
        dpaVar12.a = dpb.a;
        dpaVar12.b = dpc.c;
        dpaVar12.c = dpd.a;
        dpaVar12.e = dpe.c;
        dpa dpaVar13 = new dpa(null);
        dpaVar13.d(16);
        dpaVar13.e(32);
        dpaVar13.g(16);
        dpaVar13.f(16);
        dpaVar13.a = dlv.c;
        dpaVar13.f = dlw.c;
        dpaVar12.b(dpaVar13.c());
        map.put("ECIES_P256_COMPRESSED_HKDF_HMAC_SHA256_AES128_CTR_HMAC_SHA256_RAW", dpaVar12.a());
        drrVar.b(DesugarCollections.unmodifiableMap(map));
        drs.a.b(doz.a);
        drs.a.b(doz.b);
        drn.a.c(doz.d, dpf.class);
        dra.a.b(doz.e, true);
        dra.a.b(doz.c, false);
        dsa dsaVar2 = dqk.a;
        if (!doo.a(doo.a)) {
            throw new GeneralSecurityException("Registering HPKE Hybrid Encryption is not supported in FIPS mode");
        }
        drx drxVar2 = dpp.a;
        drt drtVar2 = drt.a;
        drtVar2.e(dpp.a);
        drtVar2.f(dpp.b);
        drtVar2.g(dpp.c);
        drtVar2.h(dpp.e);
        drtVar2.g(dpp.d);
        drtVar2.h(dpp.f);
        drr drrVar2 = drr.a;
        HashMap map2 = new HashMap();
        enh enhVar6 = new enh(null);
        enhVar6.c = dpm.a;
        enhVar6.d = dpl.f;
        enhVar6.b = dpk.a;
        enhVar6.a = dpi.a;
        map2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_128_GCM", enhVar6.i());
        enh enhVar7 = new enh(null);
        enhVar7.c = dpm.c;
        enhVar7.d = dpl.f;
        enhVar7.b = dpk.a;
        enhVar7.a = dpi.a;
        map2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_128_GCM_RAW", enhVar7.i());
        enh enhVar8 = new enh(null);
        enhVar8.c = dpm.a;
        enhVar8.d = dpl.f;
        enhVar8.b = dpk.a;
        enhVar8.a = dpi.b;
        map2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_256_GCM", enhVar8.i());
        enh enhVar9 = new enh(null);
        enhVar9.c = dpm.c;
        enhVar9.d = dpl.f;
        enhVar9.b = dpk.a;
        enhVar9.a = dpi.b;
        map2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_256_GCM_RAW", enhVar9.i());
        enh enhVar10 = new enh(null);
        enhVar10.c = dpm.a;
        enhVar10.d = dpl.f;
        enhVar10.b = dpk.a;
        enhVar10.a = dpi.c;
        map2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_CHACHA20_POLY1305", enhVar10.i());
        enh enhVar11 = new enh(null);
        enhVar11.c = dpm.c;
        enhVar11.d = dpl.f;
        enhVar11.b = dpk.a;
        enhVar11.a = dpi.c;
        map2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_CHACHA20_POLY1305_RAW", enhVar11.i());
        enh enhVar12 = new enh(null);
        enhVar12.c = dpm.a;
        enhVar12.d = dpl.a;
        enhVar12.b = dpk.a;
        enhVar12.a = dpi.a;
        map2.put("DHKEM_P256_HKDF_SHA256_HKDF_SHA256_AES_128_GCM", enhVar12.i());
        enh enhVar13 = new enh(null);
        enhVar13.c = dpm.c;
        enhVar13.d = dpl.a;
        enhVar13.b = dpk.a;
        enhVar13.a = dpi.a;
        map2.put("DHKEM_P256_HKDF_SHA256_HKDF_SHA256_AES_128_GCM_RAW", enhVar13.i());
        enh enhVar14 = new enh(null);
        enhVar14.c = dpm.a;
        enhVar14.d = dpl.a;
        enhVar14.b = dpk.a;
        enhVar14.a = dpi.b;
        map2.put("DHKEM_P256_HKDF_SHA256_HKDF_SHA256_AES_256_GCM", enhVar14.i());
        enh enhVar15 = new enh(null);
        enhVar15.c = dpm.c;
        enhVar15.d = dpl.a;
        enhVar15.b = dpk.a;
        enhVar15.a = dpi.b;
        map2.put("DHKEM_P256_HKDF_SHA256_HKDF_SHA256_AES_256_GCM_RAW", enhVar15.i());
        enh enhVar16 = new enh(null);
        enhVar16.c = dpm.a;
        enhVar16.d = dpl.b;
        enhVar16.b = dpk.b;
        enhVar16.a = dpi.a;
        map2.put("DHKEM_P384_HKDF_SHA384_HKDF_SHA384_AES_128_GCM", enhVar16.i());
        enh enhVar17 = new enh(null);
        enhVar17.c = dpm.c;
        enhVar17.d = dpl.b;
        enhVar17.b = dpk.b;
        enhVar17.a = dpi.a;
        map2.put("DHKEM_P384_HKDF_SHA384_HKDF_SHA384_AES_128_GCM_RAW", enhVar17.i());
        enh enhVar18 = new enh(null);
        enhVar18.c = dpm.a;
        enhVar18.d = dpl.b;
        enhVar18.b = dpk.b;
        enhVar18.a = dpi.b;
        map2.put("DHKEM_P384_HKDF_SHA384_HKDF_SHA384_AES_256_GCM", enhVar18.i());
        enh enhVar19 = new enh(null);
        enhVar19.c = dpm.c;
        enhVar19.d = dpl.b;
        enhVar19.b = dpk.b;
        enhVar19.a = dpi.b;
        map2.put("DHKEM_P384_HKDF_SHA384_HKDF_SHA384_AES_256_GCM_RAW", enhVar19.i());
        enh enhVar20 = new enh(null);
        enhVar20.c = dpm.a;
        enhVar20.d = dpl.c;
        enhVar20.b = dpk.c;
        enhVar20.a = dpi.a;
        map2.put("DHKEM_P521_HKDF_SHA512_HKDF_SHA512_AES_128_GCM", enhVar20.i());
        enh enhVar21 = new enh(null);
        enhVar21.c = dpm.c;
        enhVar21.d = dpl.c;
        enhVar21.b = dpk.c;
        enhVar21.a = dpi.a;
        map2.put("DHKEM_P521_HKDF_SHA512_HKDF_SHA512_AES_128_GCM_RAW", enhVar21.i());
        enh enhVar22 = new enh(null);
        enhVar22.c = dpm.a;
        enhVar22.d = dpl.c;
        enhVar22.b = dpk.c;
        enhVar22.a = dpi.b;
        map2.put("DHKEM_P521_HKDF_SHA512_HKDF_SHA512_AES_256_GCM", enhVar22.i());
        enh enhVar23 = new enh(null);
        enhVar23.c = dpm.c;
        enhVar23.d = dpl.c;
        enhVar23.b = dpk.c;
        enhVar23.a = dpi.b;
        map2.put("DHKEM_P521_HKDF_SHA512_HKDF_SHA512_AES_256_GCM_RAW", enhVar23.i());
        drrVar2.b(DesugarCollections.unmodifiableMap(map2));
        drs.a.b(dqk.a);
        drs.a.b(dqk.b);
        drn.a.c(dqk.d, dpn.class);
        dra.a.b(dqk.e, true);
        dra.a.b(dqk.c, false);
    }
}
