package defpackage;

import java.util.Arrays;
import java.util.HashMap;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class qk {
    int a;
    public final qn b = new qn();
    public final qm c = new qm();
    public final ql d = new ql();
    public final qo e = new qo();
    public HashMap f = new HashMap();
    qj g;

    public final void a(qf qfVar) {
        ql qlVar = this.d;
        qfVar.e = qlVar.j;
        qfVar.f = qlVar.k;
        qfVar.g = qlVar.l;
        qfVar.h = qlVar.m;
        qfVar.i = qlVar.n;
        qfVar.j = qlVar.o;
        qfVar.k = qlVar.p;
        qfVar.l = qlVar.q;
        qfVar.m = qlVar.r;
        qfVar.n = qlVar.s;
        qfVar.o = qlVar.t;
        qfVar.s = qlVar.u;
        qfVar.t = qlVar.v;
        qfVar.u = qlVar.w;
        qfVar.v = qlVar.x;
        qfVar.leftMargin = qlVar.H;
        qfVar.rightMargin = this.d.I;
        qfVar.topMargin = this.d.J;
        qfVar.bottomMargin = this.d.K;
        ql qlVar2 = this.d;
        qfVar.A = qlVar2.T;
        qfVar.B = qlVar2.S;
        qfVar.x = qlVar2.P;
        qfVar.z = qlVar2.R;
        qfVar.G = qlVar2.y;
        qfVar.H = qlVar2.z;
        qfVar.p = qlVar2.B;
        qfVar.q = qlVar2.C;
        qfVar.r = qlVar2.D;
        qfVar.I = qlVar2.A;
        qfVar.X = qlVar2.E;
        qfVar.Y = qlVar2.F;
        qfVar.M = qlVar2.V;
        qfVar.L = qlVar2.W;
        qfVar.O = qlVar2.Y;
        qfVar.N = qlVar2.X;
        qfVar.aa = qlVar2.an;
        qfVar.ab = qlVar2.ao;
        qfVar.P = qlVar2.Z;
        qfVar.Q = qlVar2.aa;
        qfVar.T = qlVar2.ab;
        qfVar.U = qlVar2.ac;
        qfVar.R = qlVar2.ad;
        qfVar.S = qlVar2.ae;
        qfVar.V = qlVar2.af;
        qfVar.W = qlVar2.ag;
        qfVar.Z = qlVar2.G;
        qfVar.c = qlVar2.h;
        qfVar.a = qlVar2.f;
        qfVar.b = qlVar2.g;
        qfVar.width = qlVar2.d;
        qfVar.height = this.d.e;
        ql qlVar3 = this.d;
        String str = qlVar3.am;
        if (str != null) {
            qfVar.ac = str;
        }
        qfVar.ad = qlVar3.aq;
        qfVar.setMarginStart(qlVar3.M);
        qfVar.setMarginEnd(this.d.L);
        qfVar.a();
    }

    public final /* bridge */ /* synthetic */ Object clone() {
        qk qkVar = new qk();
        ql qlVar = qkVar.d;
        ql qlVar2 = this.d;
        qlVar.b = qlVar2.b;
        qlVar.d = qlVar2.d;
        qlVar.c = qlVar2.c;
        qlVar.e = qlVar2.e;
        qlVar.f = qlVar2.f;
        qlVar.g = qlVar2.g;
        qlVar.h = qlVar2.h;
        qlVar.i = qlVar2.i;
        qlVar.j = qlVar2.j;
        qlVar.k = qlVar2.k;
        qlVar.l = qlVar2.l;
        qlVar.m = qlVar2.m;
        qlVar.n = qlVar2.n;
        qlVar.o = qlVar2.o;
        qlVar.p = qlVar2.p;
        qlVar.q = qlVar2.q;
        qlVar.r = qlVar2.r;
        qlVar.s = qlVar2.s;
        qlVar.t = qlVar2.t;
        qlVar.u = qlVar2.u;
        qlVar.v = qlVar2.v;
        qlVar.w = qlVar2.w;
        qlVar.x = qlVar2.x;
        qlVar.y = qlVar2.y;
        qlVar.z = qlVar2.z;
        qlVar.A = qlVar2.A;
        qlVar.B = qlVar2.B;
        qlVar.C = qlVar2.C;
        qlVar.D = qlVar2.D;
        qlVar.E = qlVar2.E;
        qlVar.F = qlVar2.F;
        qlVar.G = qlVar2.G;
        qlVar.H = qlVar2.H;
        qlVar.I = qlVar2.I;
        qlVar.J = qlVar2.J;
        qlVar.K = qlVar2.K;
        qlVar.L = qlVar2.L;
        qlVar.M = qlVar2.M;
        qlVar.N = qlVar2.N;
        qlVar.O = qlVar2.O;
        qlVar.P = qlVar2.P;
        qlVar.Q = qlVar2.Q;
        qlVar.R = qlVar2.R;
        qlVar.S = qlVar2.S;
        qlVar.T = qlVar2.T;
        qlVar.U = qlVar2.U;
        qlVar.V = qlVar2.V;
        qlVar.W = qlVar2.W;
        qlVar.X = qlVar2.X;
        qlVar.Y = qlVar2.Y;
        qlVar.Z = qlVar2.Z;
        qlVar.aa = qlVar2.aa;
        qlVar.ab = qlVar2.ab;
        qlVar.ac = qlVar2.ac;
        qlVar.ad = qlVar2.ad;
        qlVar.ae = qlVar2.ae;
        qlVar.af = qlVar2.af;
        qlVar.ag = qlVar2.ag;
        qlVar.ah = qlVar2.ah;
        qlVar.ai = qlVar2.ai;
        qlVar.aj = qlVar2.aj;
        qlVar.am = qlVar2.am;
        int[] iArr = qlVar2.ak;
        if (iArr == null || qlVar2.al != null) {
            qlVar.ak = null;
        } else {
            qlVar.ak = Arrays.copyOf(iArr, iArr.length);
        }
        qlVar.al = qlVar2.al;
        qlVar.an = qlVar2.an;
        qlVar.ao = qlVar2.ao;
        qlVar.ap = qlVar2.ap;
        qlVar.aq = qlVar2.aq;
        qm qmVar = qkVar.c;
        qm qmVar2 = this.c;
        qmVar.b = qmVar2.b;
        qmVar.c = qmVar2.c;
        qmVar.e = qmVar2.e;
        qmVar.f = qmVar2.f;
        qmVar.g = qmVar2.g;
        qmVar.j = qmVar2.j;
        qmVar.h = qmVar2.h;
        qmVar.i = qmVar2.i;
        qn qnVar = qkVar.b;
        qn qnVar2 = this.b;
        qnVar.a = qnVar2.a;
        qnVar.b = qnVar2.b;
        qnVar.d = qnVar2.d;
        qnVar.e = qnVar2.e;
        qnVar.c = qnVar2.c;
        qo qoVar = qkVar.e;
        qo qoVar2 = this.e;
        qoVar.b = qoVar2.b;
        qoVar.c = qoVar2.c;
        qoVar.d = qoVar2.d;
        qoVar.e = qoVar2.e;
        qoVar.f = qoVar2.f;
        qoVar.g = qoVar2.g;
        qoVar.h = qoVar2.h;
        qoVar.i = qoVar2.i;
        qoVar.j = qoVar2.j;
        qoVar.k = qoVar2.k;
        qoVar.l = qoVar2.l;
        qoVar.m = qoVar2.m;
        qoVar.n = qoVar2.n;
        qoVar.o = qoVar2.o;
        qkVar.a = this.a;
        qkVar.g = this.g;
        return qkVar;
    }
}
